#!/usr/bin/env bash

lord --verbose << "EOF"
Fix 'make genesis', I'm getting this:

./build.py --book "Genesis" --output "genesis.epub"
[ebook] Starting EPUB build: /home/jason/obsidian/We The Nameless/ebook/genesis.epub
[ebook] Source document: /home/jason/obsidian/We The Nameless/master.tex
[ebook] Pandoc: /run/current-system/sw/bin/pandoc
[ebook] Generating Markdown from 50 included TeX files...
[ebook] Generated 1,715,374-byte manuscript (50 chapters, 1559 verses)
[ebook] Using the master-style XHTML title page as the cover
[ebook] Running Pandoc to package EPUB 3...
[ebook] Running EPUB package and link validation...
[validate] valid package: 8 XHTML documents, 27 resources
[ebook] Running EPUBCheck: /run/current-system/sw/bin/epubcheck
Validating using EPUB version 3.3 rules.
ERROR(RSC-007): ./genesis.epub/EPUB/styles/stylesheet1.css(1,40): Referenced resource "EPUB/fonts/noto-sans-regular.ttf" could not be found in the EPUB.

Check finished with errors
Messages: 0 fatals / 1 error / 0 warnings / 0 infos

EPUBCheck completed
make: *** [Makefile:25: genesis] Error 1
EOF
