#!/usr/bin/env bash

lord --verbose << "EOF"
Exodus 14:10. Attribute "And the children of Israel cried out to YHWH" to P.

Exodus 14:21.
    1. Attribute "And the water was split." to P.
    2. Add \fC{REF: In the J Red Sea story, the Hebrew uses the same term for dry ground (ḥārābâ) that is used in the J flood story (Gen 7:22). Meanwhile, in the P Red Sea story, the Hebrew uses the same term for dry ground (yabbāšâ) that is used in the P flood (and creation) story (Gen 1:9,10; 8:14).}

Exodus 15:1{Let me sing} to 15:18. Attribute this to the oldest version of Proto Sinaitic font you can find in the \protoX commands.

Exodus 15:26. Add footnote:
\fC{REF: Exod 15:26 has more phrases that sound Deuteronomistic than any other passage in Genesis through Numbers. Still, it is uncertain and may be E, which has other similarities to Deuteronomistic language. (See the note on Exod 12:24.)}

Exodus 18:2. "after her being sent off" should be attributed to RJE.

Exodus 20:2-10 and 20:12-17 should be Other, Exodus 20:11 should be R, Exodus 20:18-26 is E.

Exodus 21-23 is all E.

Exodus 24:1-14 is E.

Exodus 24:18.
- "And Moses came inside the cloud" is P
- "and went up into the mountain." is R
- "And Moses was in the mountain forty days and forty nights." is J

Exodus 34:1.
- "And YHWH said to Moses, “Carve two tablets of stones" is J
- "like the first ones, and I’ll write on the tablets the words that were on the first tablets, which you shattered." is RJE.

Exodus 34:1. Add footnote:
\fC{REF: The tablets in E are shattered. Now comes the J account of the tablets. In the combined JE text, it would be awkward to picture God just commanding Moses to make some tablets, as if there were no history to this matter, so RJE adds the explanation that these are a replacement for the earlier tablets that were shattered. In E the tablets that are shattered are never said to be replaced. This suggests that, according to E, the ark that is housed in the Temple in Judah to the south either contains broken tablets or no tablets at all. As in other places, the northern Israel source E has clashing religious symbols from those of the southern kingdom of Judah. See the Collection of Evidence, pp. 19, 21.}

Exodus 34:4. Attribute this to the mixed JE source, except for "like the first ones," which is RJE.

Exodus 34:6.
- Add footnote: \fC{REF: This famous formula in J emphasizes the merciful over the just side of God: mercy, grace, kindness. As noted in the Collection of Evidence (p. 12), P never uses these words or several other words relating to mercy. P rather emphasizes the just side of God. This is an important example of the pervasive way in which the Bible became more than the sum of its parts when the Redactor combined the sources. J (and E and D) emphasized the merciful side of God; P emphasized the just side. The final version of the united Torah now brings the two sides together in a new balance, conveying a picture of God who is torn between His justice and His mercy—which has been a central element of the conception of God in Judaism and Christianity ever since.}

Exodus 34:27. Add footnote: \fC{REF: This famous formula in J emphasizes the merciful over the just side of God: mercy, grace, kindness. As noted in the Collection of Evidence (p. 12), P never uses these words or several other words relating to mercy. P rather emphasizes the just side of God. This is an important example of the pervasive way in which the Bible became more than the sum of its parts when the Redactor combined the sources. J (and E and D) emphasized the merciful side of God; P emphasized the just side. The final version of the united Torah now brings the two sides together in a new balance, conveying a picture of God who is torn between His justice and His mercy—which has been a central element of the conception of God in Judaism and Christianity ever since.}




EOF
