#!/usr/bin/env bash

lord --verbose << "EOF"
Here we go!

Following the rules for translation laid out in the file translation-megaprompt.txt,
I want you to read through the first book you find in heb/ that you don't find in eng/,
and translate it into a set of files in eng/ that correspond exactly to the files in heb/,
as if the translation had been painstakingly carried out over years by the person described
in the file translation-megaprompt.txt. Add footnotes in the generated english, of the same
type you find in the footnotes in eng/[1-5]-*, whenever you encounter a hebrew verse in the heb/
books heb/6-* and onward that you have an interesting comment about, or which you think the translator
described in translation-megaprompt.txt might have an interesting comment about. Make sure to separate
any comments you make from the ongoing translation, and remember: accurately reproducing his translation
style is the most important thing by far. Any additional comments are optional, and just for fun.

You can use eng/kjv.txt if it helps to have an english scaffolding, but you MUST not leave
any kjv diction in the final translation. Your goal is to sound like Friedman, no matter how
much work it takes to do so.

Do that now, and make it perfect.
EOF
