#!/usr/bin/env bash

lord --verbose << "EOF"
I don't like how you implemented \COMMENTARY in the most recent commit.
I want something that scales.
Let's start by reverting the changes you made to the Makefile and main.tex,
and I want us to make \COMMENTARY to be a variable in a different way.
Let's implement a minimal version of something like a "theme".

I want you to create a config.tex, and do some plain \def's in there.
Make the Makefile simple like it used to be.
To change the config, we have to edit config.tex.

main.tex includes config.tex before it does anything else.
Maybe the variables in there are called \ConfigSomething
so we always know when we're looking at something that's
defined in config.tex.

For now, I want you to support the following config keys.

1. \ConfigCommentary
    A boolean that says whether to include the final 4-5 lines
    at the bottom of \Verse that adds my commentary.

2. \ConfigTheme
    Currently there should be only two values:
    light: all current colors and fonts and stuff
    dark: somehow apply the following changes:

\definecolor{bg}{HTML}{30383e}
\definecolor{fg}{HTML}{d2c6aa}
\definecolor{Jcolor}{HTML}{98c37d}
\definecolor{Ecolor}{HTML}{fde599}
\definecolor{Pcolor}{HTML}{739feb}
\definecolor{Rcolor}{HTML}{d36463}
\pagecolor{bg}
\color{fg}

That's all I want from you for now.

Make it good.
EOF
