#!/usr/bin/env bash

lord --verbose << "EOF"
Latex up the thing below into a table using the \Table{} primitive from master.tex and add it to the commentary block in 01-genesis/25.tex

DO NOT BUILD THE BOOK! YOU ALWAYS FUCK UP WHEN YOU BUILD IT.

------------------------------------------------------------------------

## Genesis 25:26

------------------------------------------------------------------------

²⁶ And after that his brother came out, and his hand was holding Esau’s heel, and he called his name Jacob. And Isaac was sixty years old at their birth.

Ok here's another great one.

| Hebrew | Transliteration | Meaning                |
| ------ | --------------- | ---------------------- |
| ואחרי  | weʾaḥare        | and afterward          |
| כן     | khen            | thus / so              |
| יצא    | yatsaʾ          | came out               |
| אחיו   | ʾaḥiw           | his brother            |
| וידו   | weyado          | and his hand           |
| אחזת   | ʾoḥezet         | grasping / holding     |
| בעקב   | baʿaqev         | the heel of            |
| עשו    | ʿEsaw           | Esau                   |
| ויקרא  | wayyiqraʾ       | and he called          |
| שמו    | shemo           | his name               |
| יעקב   | Yaʿaqov         | Jacob                  |
| ויצחק  | weYitsḥaq       | and Isaac              |
| בן     | ben             | [was] a son of / [was] |
| ששים   | shishim         | sixty                  |
| שנה    | shanah          | years                  |
| בלדת   | beledet         | when giving birth to   |
| אתם    | ʾotam           | them                   |

He's called \heb{יעקב} because he came out holding Esau's \heb{עקב}.

Everyone always comments on the \heb{עקב} part of the pun, but there's another one in there too.

Anyone?

Read it again.

He's called \paleo{𐤉𐤏𐤒𐤁} because he came out holding Esau's \paleo{𐤏𐤒𐤁}.

Almost the same word, but differs by a letter.

His name is \paleo{𐤏𐤒𐤁} with a \paleo{𐤉} stuck on it.

And the letter \paleo{𐤉} means hand.

J is truly the Greatest Of All Time.
---

To recap:

Latex up the thing below into a table using the \Table{} primitive from master.tex and add it to the commentary block in 01-genesis/25.tex

DO NOT BUILD THE BOOK! YOU ALWAYS FUCK UP WHEN YOU BUILD IT.
EOF
