#!/usr/bin/env bash

lord --verbose << "EOF"
Fix these warnings

Underfull \hbox (badness 10000) in paragraph at lines 2277--2277
\TU/DejaVuSansMono(0)/m/n/9 mand-ments, which may well have been a joke. J is f
[][]\TU/FreeSerif(1)/m/n/9 oun-da-tional
[5] [6]
Overfull \hbox (4.5176pt too wide) in paragraph at lines 2277--2277
[]|\TU/proto-sinaitic-15.ttf(0)/m/n/9 abgsh-wZxjyklmn]pc-

Underfull \hbox (badness 4084) in paragraph at lines 2277--2277
[]|\TU/english-im-fell-english-sc-regular.ttf(0)/m/n/9 Song of the Sea uses the
 old-est Proto-

Underfull \hbox (badness 10000) in paragraph at lines 2277--2277
[]|\TU/english-im-fell-english-sc-regular.ttf(0)/m/n/9 Early Is-raelite po-etry
 and the old-est

Underfull \hbox (badness 10000) in paragraph at lines 2277--2277
\TU/english-im-fell-english-sc-regular.ttf(0)/m/n/9 Deuteron-omy ma-te-rial use
 the sec-ond

Underfull \hbox (badness 2368) in paragraph at lines 2277--2277
[]|\TU/english-im-fell-english-sc-regular.ttf(0)/m/n/9 Num-bers 21 and the old
Bal-aam po-ems in

Underfull \hbox (badness 10000) in paragraph at lines 2277--2277

EOF
