#!/usr/bin/env bash

lord --verbose << "EOF"
Whenever I build the second time to generate the TOC, I get this:

fdist/tex/context/base/mkii/supp-pdf.mkii
[Loading MPS to PDF converter (version 2006.09.02).]
)
(/nix/store/k2ky0xkabhmykhrvg5b53zhrslhkcq98-texlive-2025-r78234-final-env-texm
fdist/tex/latex/epstopdf-pkg/epstopdf-base.sty
(/nix/store/k2ky0xkabhmykhrvg5b53zhrslhkcq98-texlive-2025-r78234-final-env-texm
fdist/tex/latex/latexconfig/epstopdf-sys.cfg)) (./build/master.out)
(./build/master.out) [1{/nix/store/hzws0w5d1rlapxjk8dyksicn9cifanap-texlive-202
5-r78234-final-env/share/texmf-var/fonts/map/pdftex/updmap/pdftex.map}]
[2] [3] (./build/master.toc) [4] [5] [6] [7] [8] [1] (./01-genesis/01.tex
[2] [3] [4] [5] [6] [7] [8] [9] [10] [11] [12] [13] [14] [15] [16] [17]
[18]) [19] (./01-genesis/02.tex
./01-genesis/02.tex:2: Missing control sequence inserted.
<inserted text>
                \inaccessible
l.2 \Chapter{2}

 4295 words of node memory still in use:
   4 hlist, 12 rule, 2 disc, 2 local_par, 3 dir, 55 glue, 9 kern, 5 penalty, 24
 glyph, 865 attribute, 124 glue_spec, 416 attribute_list, 1 temp, 4 if_stack, 3
 write, 12 pdf_start_link, 11 pdf_end_link, 1 pdf_dest, 12 pdf_action nodes
   avail lists: 1:3,2:25729,3:292,4:44,5:2847,6:75,7:8403,8:2,9:565,10:33,11:54
4
./01-genesis/02.tex:2:  ==> Fatal error occurred, no output PDF file produced!
Transcript written on master.log.
make[1]: *** [Makefile:34: master.pdf] Error 1
make[1]: Leaving directory '/home/jason/Desktop/stuff/obsidian/We The Nameless'
make: *** [Makefile:23: again] Error 2

===

Fix the build, as best you can.

DO NOT BUILD THE DOCUMENT! You always go into stupid loops when you do that. Just try to fix the build. I'll do the real build.
EOF
