#!/usr/bin/env bash

lord --verbose << "EOF"
I previously gave you this prompt:

### PROMPT 1

Make me a build system that works as follows.

1. I want an ncurses inferface written in python and stored in bin/.
2. I want it to be 4 blocks wide and 3 blocks high, dividing the terminal space roughly equally between the rows and columns.
3. I want each block to show the build progress for one of each of the 12 books, when we're running a build.
4. I want the interface to only appear when I type 'make parallel'. The current 'make' should be the same as now.
5. I want 'make parallel' to run a specific python program, it's up to you if that's the same program as the ncurses interface, one program is fine.
6. I want that python program to use multiprocessing to run 12 workers, each of which runs 1 copy of the lualatex build process: one process for each of the 12 books.
7. I want that python program to use a producer consumer pattern within the workers so that each worker parses the stdout of its lualatex process and prints nice colored text, one line per book-chapter that compiles, in a nice gentle bold green, white, and blue color scheme that looks nice with a dark terminal background. You can use the \$gre, \$blu, and \$whi and \$end variables below for that:

end="\e[00m"
bla="${end}\e[1;30m"
red="${end}\e[1;31m"
gre="${end}\e[1;32m"
yel="${end}\e[1;33m"
blu="${end}\e[1;34m"
pur="${end}\e[1;35m"
cya="${end}\e[1;36m"
gra="${end}\e[1;37m"
whi="${end}\e[1;39m"

8. I want the build process to saturate all 12 of my cores, so we get a proper quick build.
9. Don't change any existing files to do that, this is an experiment, so to start just create a par/ directory, copy the Makefile, master.tex, and 01-genesis through 12-* down into there along with fonts/, and modify those files, aggressibely as needed, to see if you can get a nice system that accomplishes all of the above in a nice non-fragile easily debuggable way.


### PROMPT 2

You seem to have done that! Nice! Now, I want you to integrate the experiment you did in the par/ directory into the main repo root, deleting anything redundant, and fixing up any bits of the Makefile or build system so that 'make' (the sequential standard one that builds in build/) and 'make parallel' (the parallel ncurses one that builds in build-par, which should now build in build/parallel/) don't conflict with each other.

Also, make the python ncurses interface detect when all 12 books are done compiling, give a done message and exit, then either in the python interface or the Makefile (your call) do a pdfunite if necessary and open the resulting pdf.


### PROMPT 3

Great! It seems to be working at first glance. Now just make sure the title page and front matter get built. Don't allocate those to any of the 12 processes unless you have to. I asked you for a version of this prompt before but you allocated the front matter to the Genesis process, and it made everything sequential until Genesis finished. Don't do that. Ncurses interface should say compiling front matter, then fork, then do the twelve. Actually I'm not married to that. Just make it robust and make the decisions you think are best, but make sure it's not sequential until Genesis finishes. Make a thin bar at the top that shows the progress prior to the beginning of the 12 books parallel compiling, if you need a sequential initial step. Optional, but if you need it, do it like that.

EOF
