#!/usr/bin/env bash

lord --verbose << "EOF"
Book Typos to Fix:

1 Samuel 17:23. Attribute resumptive repetition to the Deuteronomistic editor using \\hDtrH and \\eDtrH add a source profile to master.tex with non-bold font, redactor background, and Dtr1 foreground color.

1 Samuel 22:1 escapea should be escapes.

1 Samuel 22:8 say "Some translations omit this joke, arguing that it is far more obscure than it is funny. Others disagree. Still others have argued "What?", which remains the majority view among scholars to this day.

1 Sam 22:10 needs "gets".

1 Samuel 22:12 needs "See note on 22:8."
EOF
