#!/usr/bin/env bash

lord --verbose << "EOF"
eng/ is the current default english translation, as markdown.
com/ is the current default english translation, as markdown, with any commentary I happen to have written while out walking away from my laptop.

Whenever you find a bit of commentary in com/ that isn't in eng/, I want you to:

1. Find the corresponding book, chapter, and verse in [01][0-9]*/*.tex
2. Add the commentary for each such verse in com/ to the lualatex files there.
3. Be idempotent: If you find a verse already has the same commentary in the .tex file that corresponds to a verse in some file in com/, then do nothing for that verse.
4. Remember to change any markdown-isms you find in the com/ commentary into equivalent latex-isms when you move the commentary from com/ to eng/
5. EDIT: DON'T DO DUMB SHIT! I want the book and its code to be simple. Don't add \par\smallskip for idiotic reasons to the tex.
   I don't know where you're getting these ideas about what I want.
   I want a simple update of the commentary in the tex files, using the commentary in com/.
   You should only be touching these files this time around:

    eng/01-genesis/19.md
    eng/01-genesis/20.md
    eng/01-genesis/21.md
    eng/08-samuel/2-01.md
    eng/08-samuel/2-02.md
    eng/08-samuel/2-03.md
    eng/08-samuel/2-04.md
    eng/08-samuel/2-05.md
    eng/08-samuel/2-06.md
    eng/08-samuel/2-07.md
    eng/08-samuel/2-08.md
    eng/08-samuel/2-09.md
    eng/08-samuel/2-10.md
    eng/08-samuel/2-11.md
EOF
