#!/usr/bin/env bash

lord --verbose << "EOF"

- Turn the content of new.md into tex in the format of old.tex to generate a new file master.tex

- Give the paper an aesthetically nice looking Journal layout for a journal we'll call Babel Publishing.

- Give it a convincing academic journal / publisher style layout.

- Put the Babel publishing logo somewhere with a box around it. It's this:

    \chineseA{肏}IV||\chineseA{一}
    Fʌ\korean{ㅋ}\ara{𐡅}v∨\paleo{𐤉}
    φə\paleo{𐤒}\chineseA{愛}\heb{ו}| \heb{י}

- Make all Hebrew in the paper in master.tex be toggle-able between regular hebrew and paleo-hebrew, with standard \hebrew{אדמה} throughout the paper (never any unwrapped hebrew letters) and a \renewcommand or something at the top that will optionally (if uncommented) define \hebrew{...} to be \paleo{...} or \heb{...}. Assume I have the fonts locally to make this work.

- Turn all markdownisms to latexisms, using the primitives in welibc.tex like \Table{...} and so on.

- Make sure the tables you include have grid lines.

Do that, and make it look like a real nice looking academic paper.
EOF
