#!/usr/bin/env bash

lord --verbose << "EOF"
In the ebook/, when I run 'make genesis', I notice the following things that I want you to fix:

1. In Genesis 2:6-7 with the AD, ADM, ADMH stuff, the table/columns structure is good in the book's main tex, but the ebook isn't translating it properly. All the cells are stacked vertically.

2. Soon after that, in the verse that starts with "Here we go", the 9 tables should be in a 3x3 grid. They're good in the book tex. But the ebook is stacking them all vertically, same as the item above this.

3. \ruby{}{} in the TeX isn't transpiling to css/html correctly in the ebook. Search Genesis 2 for the footnote that contains 們. Try to use html5 <ruby> if it works, or any other tactic if it doesn't, to preserve the behavior of the TeX within the ebook.

4. In the footnote that says "Perhaps a pun on the Hebrew verb {ידע} (yadá)", some macro appears to have been lost, I'm seeing literal curly braces and hebrew in the ebook.

5. In Gen 3:6, remove the linebreaks in the eng and heb in the ebook.

6. In Gen 3:10, the 'erom fraction' in the Hebrew is correctly colored and positioned, but it's somehow no longer paleo in the ebook. Also it's backwards (LTR). Fix that.

7. All the footnotes are just numbers, not superscripts in the ebook. Fix that. Also there's a space between the text and each footnote. Fix that too.

8. The table in Gen 4:7 isn't transferring correctly to the ebook. Make it a \Table{} in 01-genesis/04.tex. This one isn't an ebook fix, it's a tex fix.

9. In Gen 7:1 in the ebook, there's a mysterious [8][5000] right after 'Praise the Lord!' probably because something was transpiled wrong. Fix that.

10. Color the footnote links and text the same color as they would be in the TeX. \aA{} is foreground color, \aB{} is red, \aC{} is blue, use the same colors from master.tex.

11. Make sure that \Tables in ebook format have the bottom \hrule like they do in latex.

12. Try to fix the hieroglyph positioning in Gen 48 and Gen 12.

13. On the Source Key pages in the front matter, the two columns should be left aligned within the space they occupy. Also the redactor background colors are spilling too far to the left and right, almost as if they're a div when they should be a span. Fix that in whatever way you think is most robust.

14. P's hebrew has niqqud on the source fonts page (good) but not in the main text. Give P hebrew niqqud in the main text of the book.

15. Gen 1:3's comment text should be red, but it's black. Gen 1:1 should alternate red and blue but it's black and blue.

16. Gen 1:8 and Gen 1:14 are also black but should be red.

17. All this text should be centered, but the text around it shouldn't be. Follow the tex.

What’s bible?

Day ball. Night ball.

Moon go around. Girls bleed.

After twelve, it’s time to do it.

And do it again. The whole cycle.

Cuz the balls. The balls say so.

This should be clear.

That’s bible.

18. The \redacted{} macro should blue-out a box of text that's as long as the text inside it, but it's currently invisible. Fix that. See Gen 1:28 for an example.

19. Gen 1:21 contains black text that should be red, too-wide redactor backgrounds, and text that should be centered but isn't. Follow the tex.

20. Make LaTeX quotes ``like this'' transpile into proper unicode quotes correctly.

21. 'Cf., Chinese mythology,' and the other black text in the footnotes around there should be red.

22. The page count seems to be showing up as 59. Not sure if that's just the app I'm using, but try to fix the page count if possible so it's something sensible.

EOF
