#!/usr/bin/env bash

lord --verbose --dont-panic << "EOF"
improve bin/git-recent

Make sure the bin/git-recent command works as intended,
and add a flag -v/--verbose that will print the git
commands executed along the way to stderr before it
executes each one.
EOF
